### ISSUE TITLE
Error with encodermap

### ISSUE THREAD

**Issue by NeetuSinghYadav** [AG-Peter/encodermap#15]
I am trying to run encodermap. The input file has dihedral agles and RMSD, Rg. I am getting this error.

Nan in summary histogram for: encoder/dense_1_biases/histogram
	 [[node encoder/dense_1_biases/histogram 
However, with other system the similar file type is  running with issue.

Please let me know how to fix this. I have attached the small subset of my input file
[Input.csv](https://github.com/AG-Peter/encodermap/files/8664754/Input.csv)

**Comment by TobiasLe** [comment]
Hi, 

it is probably the same problem as discussed in this issue: #14 

If you don't (only) use inputs like dihedrals, that are in a small number range by construction, it is a good idea to normalize the input data before you feed them into EncoderMap. You could for example subtract the mean and divide by the standard deviation of your RMSD / RG values.

Normalization makes the training process of the neural network more reliable, because no matter what input data you initially have, the network will always see similar inputs.

**Comment by NeetuSinghYadav** [comment]
Thanks Tobias for the reply. I tried the  StandardScaling for RMSD and RG inputs and results are much better. However, I have a question-shall I perform the StandardScaling for RMSD and RG input only, or for whole data set. Currently I am using the cosine of dihderal angles and StandardScalesd RMSD and RG values.
