### ISSUE TITLE
Generated paths

### ISSUE THREAD

**Issue by Monte95** [AG-Peter/encodermap#5]
Hi! I've found an issue with the generated paths. From a 100ns-GROMACS trajectory I obtained the various PHI dihedrals of the simulated protein (also a Hsp, with 189 residues) during all the frames of the simulation. I converted these values in csv format and tried to modify the example you give (trp_cage.py) in order to obtain the generated structures for my protein, after Encodermap calculations.
The program runs fine, I select the points from which the generated trajectory will be drawn, and I obtain the file generated.pdb .

The problem is: when I open it with VMD, many distant atoms of the protein seem to be covalently connected, and long lines appear during the visualization.

Also, the generated structures are very far from the original structure, and all structural organization has disappeared (known conserved beta sheets become loops for example).

I'm new to this kind of calculations, so I've tried changing the various parameters in dist_sig_parameters, using the relations between a_h, b_h, a_l, b_l you give. Also I tried to set the l2_reg_constant to 0.0001 and the number of training steps to 50000.
Still the same strange generated structures persist.

I kindly ask for suggestions about what to do to get structures with lower RMSD with respect of the initial structure. Have I to increase the length of the simulation from which the dihedrals are calculated? Which values can I give the parameters? Have I to increase the number of steps? 

Thank you very much

Here I attach the modified program I used to perform the calculations:
```python
import encodermap as em
import numpy as np
import os
from math import pi
import matplotlib.pyplot as plt


###setting parameters
run_path = em.misc.run_path("./runs")
csv_path = "all_dihedrals.csv"


print("loading data ...")
high_d_data = np.loadtxt(csv_path, delimiter=",")

####SET PARAMETERS
parameters = em.Parameters()
parameters.main_path = run_path
parameters.dist_sig_parameters = (500.0, 12, 5, 1, 2, 5) #dim_h/dim_l = 6
parameters.n_steps = 50000
parameters.periodicity = 2*pi
parameters.l2_reg_constant = 0.00001

####if your data set is large you should not try to calculate 
####the pairwise distance histogram with the complete data. 
em.plot.distance_histogram(high_d_data[::10],  # e.g. use high_d_data[::10] to use every 10th point
                           parameters.periodicity,
                           parameters.dist_sig_parameters,
                           bins=50)

print("training autoencoder ...")
e_map = em.EncoderMap(parameters, high_d_data)
e_map.train()


print("projecting data ...")
low_d_projection = e_map.encode(high_d_data)


print("plotting result ...")
fig, axe = plt.subplots()
caxe = axe.scatter(low_d_projection[:, 0], low_d_projection[:, 1], c=high_d_data[:, -1], s=2.5, cmap="nipy_spectral",
                   marker="o", linewidths=0)
cbar = fig.colorbar(caxe)
cbar.set_label("rmsd")


####generate structures along path
pdb_path = "b8.pdb"
generator = em.plot.PathGenerateDihedrals(axe, e_map, pdb_path)

plt.show()
```

**Comment by TobiasLe** [comment]
Hi @Monte95,

to obtain good generated conformations for a large protein like yours it is crucial to use the variant of EncoderMap that we introduced in:
https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00675
In this variant the backbone Cartesian coordinates are reconstructed during the training process to improve the long-range order.

To use this variant, you need to use the [AngleDihedralCartesianEncoderMap](https://ag-peter.github.io/encodermap/docbuild/html/angle_dihedral_cartesian_encodermap.html) instead of the normal EncoderMap class.

I am sorry that there is no tutorial explaining how to do that (yet), but you can follow the Diubiquitin examples:
[dihedral_to_cartesian_diubi.py](https://github.com/AG-Peter/encodermap/blob/master/encodermap/examples/dihedral_to_cartesian_diubi.py
)
[dihedral_to_cartesian_diubi_analysis.py](https://github.com/AG-Peter/encodermap/blob/master/encodermap/examples/dihedral_to_cartesian_diubi_analysis.py)

Let me know if you run into any further Problems.
